//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail to info@conversiononline.co. I reply to all e-mail I receive..
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT ME.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for visiting conversiononline.co. If you have any comments, suggestions, requests, bug reports, or just want to say hello, feel free to contact me..
        /// </summary>
        internal static string ContactsBody {
            get {
                return ResourceManager.GetString("ContactsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am going to add all types of conversion here. But now here is what we have now.
        /// </summary>
        internal static string CurrentlyAvailableBody {
            get {
                return ResourceManager.GetString("CurrentlyAvailableBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently available.
        /// </summary>
        internal static string CurrentlyAvailableTitle {
            get {
                return ResourceManager.GetString("CurrentlyAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELLO.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am created this site for educatinal purposes. If you have any ideas or recomendation how i can improve it please fill free to email..
        /// </summary>
        internal static string HomePageBody {
            get {
                return ResourceManager.GetString("HomePageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free online units converter.
        /// </summary>
        internal static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online,conversion.
        /// </summary>
        internal static string HomePageKeywords {
            get {
                return ResourceManager.GetString("HomePageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Online - Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        internal static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        internal static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League[nautical].
        /// </summary>
        internal static string LeagueNautical {
            get {
                return ResourceManager.GetString("LeagueNautical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;In geometric measurements, &lt;strong&gt;length&lt;/strong&gt; is the longest dimension of an object. In other contexts &quot;length&quot; is the measured dimension of an object. For example it is possible to cut a length of a wire which is shorter than wire thickness.&lt;/p&gt;
        ///&lt;p&gt;Length may be distinguished from height, which is vertical extent, and width or breadth, which are the distance from side to side, measuring across the object at right angles to the length. Length is a measure of one dimension, whereas area is a measure [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LengthBody {
            get {
                return ResourceManager.GetString("LengthBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght conversion.
        /// </summary>
        internal static string LengthTitle {
            get {
                return ResourceManager.GetString("LengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microinch.
        /// </summary>
        internal static string Microinch {
            get {
                return ResourceManager.GetString("Microinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string Mile {
            get {
                return ResourceManager.GetString("Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeter.
        /// </summary>
        internal static string Millimeter {
            get {
                return ResourceManager.GetString("Millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result will be here.
        /// </summary>
        internal static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Use this page to convert from readable date/time to unixtime and vise versa.&lt;/p&gt; &lt;p&gt;Unix time is a single signed integer number which increments every second, without requiring the calculations to determine year, month, day of month, hour and minute required for intelligibility to humans. Modern Unix time is based on UTC, which counts time using SI seconds, and breaks up the span of time into days almost always 86 400 s long, but due to leap seconds occasionally 86 401 s this keeps the days synchronized  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnixTimeBody {
            get {
                return ResourceManager.GetString("UnixTimeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert unixtime to readable date/time.
        /// </summary>
        internal static string UnixtimePageDescription {
            get {
                return ResourceManager.GetString("UnixtimePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unixtime,conversion,online,timestamp.
        /// </summary>
        internal static string UnixtimePageKeywords {
            get {
                return ResourceManager.GetString("UnixtimePageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnixTime Conversion.
        /// </summary>
        internal static string UnixTimeTitle {
            get {
                return ResourceManager.GetString("UnixTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming services.
        /// </summary>
        internal static string UpcomingServices {
            get {
                return ResourceManager.GetString("UpcomingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string Yard {
            get {
                return ResourceManager.GetString("Yard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
